### ISSUE TITLE
Possibilité de dupliquer un service explicite dans un host

### ISSUE THREAD

**Issue by alainaas** [EyesOfNetworkCommunity/lilac#1]
Bonjour à tous,

Je fais une demande folle :

Est il possible d’avoir la possibilité de dupliquer un service explicite dans un host ? un petit bouton duplicate juste à côté sur bouton delete sur la ligne du service en question ?

A bientôt

Alain

**Comment by maubertin** [comment]
Hello Alain,

Si j'ai compris tu peux deja le faire à partir d'une recherche sur le
service via la barre d'action rapide.

@++
Mike

Le 8 juil. 2016 11:05, "Alain Astgen" <notifications@github.com> a écrit :

Bonjour à tous,

Je fais une demande folle :

Est il possible d’avoir la possibilité de dupliquer un service explicite
dans un host ? un petit bouton duplicate juste à côté sur bouton delete sur
la ligne du service en question ?

A bientôt

Alain

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EyesOfNetworkCommunity/lilac/issues/1>, or mute the
thread
<https://github.com/notifications/unsubscribe/ABTgEC4pKw30rIyoPC-tehRfIIVF5eG4ks5qThLZgaJpZM4JH2Wg>
.

**Comment by rverchere** [comment]
@alainaas ton voeux pourra être exaucé, see #15

**Comment by rverchere** [comment]
Merged!
